// Enums
export type MatterState = 
  | 'Intake'
  | 'DisputePreparation'
  | 'DisputeActive'
  | 'PartialCompliance'
  | 'ViolationConfirmed'
  | 'ReinsertionDetected'
  | 'RegulatoryReview'
  | 'Blocked'
  | 'FurnisherLiabilityTrack'
  | 'EscalationEligible'
  | 'LitigationReady'
  | 'Resolved';

export type MatterType = 'Credit' | 'Consulting' | 'Both';

export type EntityType = 'CRA' | 'Furnisher' | 'DataBroker' | 'Agency';

export type OverlayType = 'IdentityTheftDocumented' | 'MixedFileConfirmed' | 'UpstreamContainmentActive';

export type Priority = 'P0' | 'P1' | 'P2' | 'P3';

export type TaskStatus = 'Pending' | 'InProgress' | 'Done' | 'Blocked';

export type DeadlineStatus = 'Open' | 'DueSoon' | 'Overdue' | 'Closed';

export type DeadlineType = 
  | '611_30day'
  | '611_notice'
  | '605B_4biz'
  | 'Reinsertion_5biz'
  | 'CFPB_15'
  | 'CFPB_60'
  | 'FollowUp';

export type ResponseType = 
  | 'NoResponse'
  | 'Boilerplate'
  | 'Verified'
  | 'Deleted'
  | 'PartialDeleted'
  | 'Reinserted'
  | 'MOVProvided'
  | 'Other';

export type DateConfidence = 'Exact' | 'Inferred' | 'Unknown';

export type EvidenceType = 'Report' | 'Portal' | 'Mail' | 'ClientStatement' | 'Unknown';

export type ViolationTrigger = 
  | 'Missed611Deadline'
  | 'Reinsertion611a5B'
  | 'Failure605B'
  | 'NoMOV'
  | 'Boilerplate';

// Core Types
export interface Client {
  id: string;
  legalName: string;
  preferredName?: string;
  email: string;
  phone?: string;
  status: 'Active' | 'Inactive' | 'Pending';
  createdAt: Date;
  notes?: string;
}

export interface Matter {
  id: string;
  clientId: string;
  matterType: MatterType;
  title: string;
  jurisdiction?: string;
  primaryState: MatterState;
  openedAt: Date;
  closedAt?: Date;
  escalationStrategy?: string;
  overallReliabilityRating?: number;
  overlays: Overlay[];
}

export interface EntityCase {
  id: string;
  matterId: string;
  entityType: EntityType;
  entityName: string;
  state: MatterState;
  lastActionAt?: Date;
  notes?: string;
}

export interface Action {
  id: string;
  matterId: string;
  entityCaseId?: string;
  actionType: string;
  actionDate: Date;
  dateConfidence: DateConfidence;
  evidenceType: EvidenceType;
  summary: string;
  createdBy: string;
}

export interface Response {
  id: string;
  matterId: string;
  entityCaseId: string;
  receivedDate: Date;
  responseType: ResponseType;
  summary: string;
}

export interface Deadline {
  id: string;
  matterId: string;
  entityCaseId: string;
  deadlineType: DeadlineType;
  startDate: Date;
  dueDate: Date;
  status: DeadlineStatus;
  sourceActionId?: string;
}

export interface Task {
  id: string;
  matterId: string;
  entityCaseId?: string;
  relatedAccountId?: string;
  taskType: string;
  priority: Priority;
  dueDate?: Date;
  status: TaskStatus;
  autoGenerated: boolean;
  createdAt: Date;
  completedAt?: Date;
  completionNotes?: string;
}

export interface Overlay {
  id: string;
  matterId: string;
  overlayType: OverlayType;
  isActive: boolean;
  activatedAt: Date;
  deactivatedAt?: Date;
}

export interface Violation {
  id: string;
  matterId: string;
  entityCaseId: string;
  trigger: ViolationTrigger;
  statutorySection: string;
  severity: 1 | 2 | 3 | 4 | 5;
  createdAt: Date;
  evidenceAttached: boolean;
  notes?: string;
}

export interface WillfulnessScore {
  matterId: string;
  entityCaseId?: string;
  score: number;
  lastCalculatedAt: Date;
}

// Dashboard Stats
export interface DashboardStats {
  totalMatters: number;
  activeDisputes: number;
  violationsConfirmed: number;
  overdueDeadlines: number;
  tasksDueToday: number;
  reinsertionsDetected: number;
  litigationReady: number;
}

// Priority labels and descriptions
export const PRIORITY_LABELS: Record<Priority, { label: string; description: string }> = {
  P0: { label: 'Statutory', description: 'Legal deadlines - immediate action required' },
  P1: { label: 'Regulatory', description: 'CFPB/BBB/AG windows' },
  P2: { label: 'Operational', description: 'Mail proofs, client updates' },
  P3: { label: 'Maintenance', description: 'Ongoing monitoring' },
};

export const STATE_LABELS: Record<MatterState, { label: string; description: string }> = {
  Intake: { label: 'Intake', description: 'Client onboarded, collecting documents' },
  DisputePreparation: { label: 'Dispute Prep', description: 'Drafting disputes and evidence' },
  DisputeActive: { label: 'Dispute Active', description: 'Monitoring statutory deadlines' },
  PartialCompliance: { label: 'Partial Compliance', description: 'Some items deleted, others remain' },
  ViolationConfirmed: { label: 'Violation Confirmed', description: 'CRA noncompliance established' },
  ReinsertionDetected: { label: 'Reinsertion Detected', description: 'Previously deleted item reappeared' },
  RegulatoryReview: { label: 'Regulatory Review', description: 'CFPB complaint filed' },
  Blocked: { label: 'Blocked', description: 'Process stalled - authorization needed' },
  FurnisherLiabilityTrack: { label: 'Furnisher Track', description: 'Section 623(b) duties active' },
  EscalationEligible: { label: 'Escalation Eligible', description: 'BBB, AG, litigation pathways open' },
  LitigationReady: { label: 'Litigation Ready', description: 'Willfulness threshold met' },
  Resolved: { label: 'Resolved', description: 'All items removed, monitoring' },
};

export const ENTITY_LABELS: Record<EntityType, string> = {
  CRA: 'Credit Reporting Agency',
  Furnisher: 'Furnisher',
  DataBroker: 'Data Broker',
  Agency: 'Regulatory Agency',
};

export const DEADLINE_LABELS: Record<DeadlineType, string> = {
  '611_30day': '§611 30-Day Reinvestigation',
  '611_notice': '§611 35-Day Results Notice',
  '605B_4biz': '§605B 4-Business Day Blocking',
  'Reinsertion_5biz': 'Reinsertion 5-Business Day',
  'CFPB_15': 'CFPB 15-Day Response',
  'CFPB_60': 'CFPB 60-Day Resolution',
  'FollowUp': 'Follow-Up',
};
